server:
  port: 8000
spring:
  application:
    # 微服务名称，生产者集群，这个要写的一样，这是这个集群的关键
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源的类型
    driver-class-name: com.mysql.cj.jdbc.Driver    #驱动
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=UTC&useSSL=false
    username: root
    password: '@Root123'

mybatis:
  mapperLocations: classpath:mapper/*.xml  # mapper文件路径
  type-aliases-package: com.springcloud.pojo # 扫描实体类取别名

eureka:
  client:
    # false 表示不想注册中心注册自己，true注册到服务中心
    register-with-eureka: true
    # false表示自己就是注册中心，职责就是维护服务实例，并不需要检索服务,true表示从EurekaServer抓取已有的注册信息，(集群必须设置为true才能配合ribbon使用负载均衡)
    fetch-registry: true
    service-url:
      #设置与Eureka server的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 实例显示id
    instance-id: payment8000
    # 鼠标放上去显示ip地址
    prefer-ip-address: true
    #Eureka客户端向服务器端发送心跳的时间间隔单位是秒，默认是30秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端再收到最后一次心跳后等待时间上限，单位为秒默认是90秒，超时将剔除服务，这个值至少要大于lease-renewal-interval-in-seconds
    lease-expiration-duration-in-seconds: 2